name: Build and Publish

on: 
  release:
    types: [published]

jobs: 
  build_and_push_image:
      runs-on: ubuntu-latest
      steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      
      - name: Setup Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Github Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build Image and Push to GHCR
        uses: docker/build-push-action@v4
        with:
          platforms: linux/arm/v7
          context: .
          tags: ghcr.io/chocolatetilt/tiltbotgo:latest
          push: true
