name: Build and Publish

on:
  release:
    types: [published]

jobs:
  build_and_push_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Image and Push to GHCR
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/arm/v7
          tags: ghcr.io/chocolatetilt/tiltbotgo:latest
          push: true
